{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "my-odoo.serviceAccountName" . }}
  labels:
{{ include "my-odoo.labels" . | nindent 4 }}
{{- end -}}
