apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask
  name: flask-deployment
  namespace: qlinik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  strategy: {}
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - image: medigoid/qlinik-api:k8s
        name: flask
        ports:
        - containerPort: 80
 
