apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: bd-flask
spec:
  selector:
    app: flask
  type: NodePort
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 8082
    # Port to forward to inside the pod
    targetPort: 5000
    # Port accessible outside cluster
    nodePort: 30027
