apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tutum
  name: tutum-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tutum
  strategy: {}
  template:
    metadata:
      labels:
        app: tutum
    spec:
      containers:
      - image: tutum/hello-world
        name: tutum
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        ports:
        - containerPort: 80
