apiVersion: v1
kind: Service
metadata:
  name: tutum-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - protocol: "TCP"
    # Port accessible inside cluster
    port: 80
    # Port to forward to inside the pod
    targetPort: 80
    # Port accessible outside cluster
    nodePort: 30001
  #externalIPs:
  #- 192.168.39.186
